---  
     - name: 'Baixa o arquivo de instalacao do Wordpress'
       get_url:
         url: https://wordpress.org/latest.tar.gz
         dest: /root/wordpress.tar.gz
       become: yes
        
     - name: 'Descompactando o arquivo do wordpress.tar.gz'
       unarchive:
         src: /root/wordpress.tar.gz
         dest: /root
         remote_src: yes
       become: yes

     - name: 'Copiando os arquivos do Wordpress para a pasta html'
       copy:
         src: /root/wordpress
         dest: /var/www/html
         remote_src: yes
       become: yes

     - name: 'Copiando arquivo de exemplo para configuração do Wordpress'
       copy:
         src: /var/www/html/wordpress/wp-config-sample.php
         dest: /var/www/html/wordpress/wp-config.php
         remote_src: yes
       become: yes

     - name: 'Configurando o wp-config para acessar o banco de dados Wordpress'     
       replace:
         path: '/var/www/html/wordpress/wp-config.php'
         regexp: "{{ item.regex }}"
         replace: "{{ item.value }}"
         backup: yes
       with_items:
         - { regex: 'database_name_here', value: 'wordpress'}
         - { regex: 'username_here', value: 'wp_admin'}
         - { regex: 'password_here', value: 'teste12345'}
       become: yes

